import { useState } from "react";
import { Activity, CheckCircle2, FileSearch, Fingerprint, ScanSearch, ShieldCheck } from "lucide-react";
import Container from "@/components/ui/Container";
import Reveal from "@/components/motion/Reveal";
import { MonoLabel } from "./primitives";
import styles from "./AlertSarSplit.module.css";

const outcomes=[
 {label:"FRAUD",icon:Activity,title:"Decision brief",status:"BLOCK RECOMMENDED",event:"EVT-FRD-4471",signals:["New device after credential reset","Impossible-travel session","Beneficiary linked to challenged payments"],brief:"ARGUS connected the payment to a newly observed device, a high-risk session and a beneficiary shared across challenged accounts. The evidence satisfies policy FRD-ATO-17 and supports blocking the transaction with analyst review."},
 {label:"BATCH AML",icon:FileSearch,title:"Investigation narrative",status:"ESCALATE FOR REVIEW",event:"CASE-AML-2048",signals:["Eleven sub-threshold deposits","Four-hop movement through a shell entity","Fan-in hub connected to nine sources"],brief:"Across the governed UDM history, ARGUS identified repeated structuring followed by rapid movement through a recently formed company and a connected fan-in hub. FundsTrace preserved the complete path and the Narrator assembled the evidence for investigator disposition."},
 {label:"ENTITY",icon:Fingerprint,title:"Resolution evidence pack",status:"MERGE APPROVED",event:"ENTITY-E-204",signals:["Name and date-of-birth agreement","Shared device and address evidence","Governed relationship confidence 0.96"],brief:"ARGUS resolved fragmented customer, account and device records into one canonical entity. Every contributing source, relationship score and merge decision remains visible and reversible for downstream risk decisions."},
 {label:"TRADE",icon:ScanSearch,title:"Supervisor review brief",status:"CONDUCT REVIEW",event:"TRD-SUP-091",signals:["Repeated bid-side layering","Ninety-seven percent cancellation pattern","Opposite-side executions after price movement"],brief:"ClickHouse detected a repeated order-and-cancel sequence across trading sessions. Market-conduct ML ranked the pattern, and agents connected the activity to trader, account and supervisory context for review."},
] as const;

export default function AlertSarSplit(){const [active,setActive]=useState(0);const item=outcomes[active];return <section className={styles.section}><Container size="wide"><Reveal className={styles.head}><MonoLabel tone="accent">INVESTIGATION OUTCOMES</MonoLabel><h2>Evidence becomes the document the reviewer needs.</h2><p>ARGUS does not force every workload into a SAR. It produces the right governed outcome for fraud, AML, entity resolution or trade supervision.</p></Reveal><div className={styles.tabs} role="tablist" aria-label="ARGUS investigation outcomes">{outcomes.map((o,i)=>{const Icon=o.icon;return <button type="button" role="tab" aria-selected={i===active} className={i===active?styles.activeTab:""} onClick={()=>setActive(i)} key={o.label}><Icon/><span>{o.label}</span></button>})}</div><div className={styles.workspace}><div className={styles.evidence}><div className={styles.panelHead}><span><i/>EVIDENCE ASSEMBLY</span><b>{item.event}</b></div><div className={styles.signalList}>{item.signals.map((s,i)=><div key={s}><span>0{i+1}</span><CheckCircle2/><p>{s}</p></div>)}</div><div className={styles.lineage}><ShieldCheck/><div><small>LINEAGE PRESERVED</small><strong>Source · detection · model · agent · human action</strong></div></div></div><div className={styles.outcome} key={item.label}><div className={styles.documentTop}><span>{item.title}</span><b>{item.status}</b></div><small>GENERATED FROM CITED CASE EVIDENCE</small><p>{item.brief}</p><div className={styles.approval}><span>HUMAN DECISION REQUIRED</span><strong>Ready for review</strong></div></div></div></Container></section>}
