import { useState } from "react";
import { Activity, BrainCircuit, CandlestickChart, Database, Fingerprint, Network, ShieldCheck } from "lucide-react";
import Container from "@/components/ui/Container";
import Reveal from "@/components/motion/Reveal";
import { MonoLabel } from "./primitives";
import styles from "./WorkloadGraphs.module.css";

const stories=[
 {id:"fraud",label:"REAL-TIME FRAUD",icon:Activity,title:"A live payment becomes a connected fraud decision.",copy:"Streaming signals connect the account, device, session and beneficiary before the transaction completes.",verdict:"BLOCK · ACCOUNT TAKEOVER",model:"BEHAVIOR ML · 0.91",nodes:[{id:"event",x:10,y:50,label:"PAYMENT",type:"EVENT",risk:"LIVE",evidence:"$8,420 · new beneficiary"},{id:"acct",x:32,y:28,label:"ACCT ·2048",type:"ACCOUNT",risk:"HIGH",evidence:"Dormant for 94 days"},{id:"device",x:32,y:72,label:"DEVICE ·9F",type:"DEVICE",risk:"NEW",evidence:"First seen 7 minutes ago"},{id:"session",x:57,y:20,label:"SESSION",type:"BEHAVIOR",risk:"0.91",evidence:"Impossible travel + reset"},{id:"payee",x:58,y:78,label:"PAYEE ·771",type:"ENTITY",risk:"HIGH",evidence:"Linked to 6 challenged payments"},{id:"ring",x:82,y:50,label:"FRAUD RING",type:"GRAPH",risk:"CRITICAL",evidence:"Shared device across 4 accounts"},{id:"action",x:105,y:50,label:"BLOCK",type:"ACTION",risk:"ACTION",evidence:"Policy FRD-ATO-17"}],edges:[['event','acct'],['event','device'],['acct','session'],['device','payee'],['session','ring',true],['payee','ring',true],['ring','action',true]]},
 {id:"aml",label:"BATCH AML",icon:Database,title:"Long-horizon UDM history exposes structured laundering.",copy:"ClickHouse evaluates complete history, ML ranks the pattern, and agents trace the connected flow into an investigation.",verdict:"ESCALATE · STRUCTURING",model:"AML PATTERN ML · 0.94",nodes:[{id:"udm",x:10,y:50,label:"UDM HISTORY",type:"CLICKHOUSE",risk:"12 MONTHS",evidence:"Transactions + parties + accounts"},{id:"cash",x:31,y:23,label:"CASH BANDS",type:"PATTERN",risk:"11 HITS",evidence:"Deposits below threshold"},{id:"burst",x:31,y:77,label:"48H BURST",type:"TEMPORAL",risk:"HIGH",evidence:"14 deposits · $138,400"},{id:"shell",x:57,y:20,label:"SHELL LLC",type:"ENTITY",risk:"HIGH",evidence:"Registered 3 weeks ago"},{id:"hub",x:57,y:80,label:"FAN-IN HUB",type:"GRAPH",risk:"9 SOURCES",evidence:"Layered unrelated senders"},{id:"ml",x:82,y:50,label:"AML ML",type:"INTELLIGENCE",risk:"0.94",evidence:"Structuring + layering pattern"},{id:"action",x:105,y:50,label:"CASE",type:"ACTION",risk:"REVIEW",evidence:"FundsTrace + Narrator agents"}],edges:[['udm','cash'],['udm','burst'],['cash','shell'],['burst','hub'],['shell','ml',true],['hub','ml',true],['ml','action',true]]},
 {id:"entity",label:"ENTITY RESOLUTION",icon:Fingerprint,title:"Fragmented records resolve into one governed identity.",copy:"Graph resolution links records by deterministic and probabilistic evidence, preserving confidence and the source of every relationship.",verdict:"RESOLVED · ENTITY E-204",model:"IDENTITY MODEL · 0.96",nodes:[{id:"party",x:10,y:22,label:"PARTY A",type:"CUSTOMER",risk:"SOURCE",evidence:"KYC name + DOB"},{id:"acct",x:10,y:50,label:"ACCOUNT",type:"CORE",risk:"SOURCE",evidence:"Owner record"},{id:"device",x:10,y:78,label:"DEVICE",type:"DIGITAL",risk:"SOURCE",evidence:"Session fingerprint"},{id:"alias",x:40,y:22,label:"ALIAS",type:"NAME",risk:"0.88",evidence:"Transliteration + address"},{id:"business",x:40,y:78,label:"BUSINESS",type:"OWNERSHIP",risk:"0.82",evidence:"Director + phone"},{id:"entity",x:72,y:50,label:"ENTITY E-204",type:"CANONICAL",risk:"0.96",evidence:"Governed merge decision"},{id:"network",x:105,y:50,label:"RISK NETWORK",type:"GRAPH",risk:"CONNECTED",evidence:"Accounts + counterparties"}],edges:[['party','alias'],['acct','entity'],['device','business'],['alias','entity',true],['business','entity',true],['entity','network',true]]},
 {id:"trade",label:"TRADE SURVEILLANCE",icon:CandlestickChart,title:"Batch surveillance connects market behavior to the actor.",copy:"ClickHouse evaluates order and execution history; ML identifies manipulation patterns, while AI and agents assemble trader and entity context.",verdict:"SUPERVISOR REVIEW · SPOOFING",model:"MARKET CONDUCT ML · 0.89",nodes:[{id:"orders",x:10,y:25,label:"ORDERS",type:"UDM",risk:"18,420",evidence:"Layering on bid side"},{id:"exec",x:10,y:75,label:"EXECUTIONS",type:"UDM",risk:"1,284",evidence:"Opposite-side fills"},{id:"cancel",x:35,y:20,label:"CANCEL RATE",type:"SIGNAL",risk:"97%",evidence:"Orders removed near touch"},{id:"price",x:35,y:80,label:"PRICE MOVE",type:"SIGNAL",risk:"+42 BPS",evidence:"Movement after displayed depth"},{id:"pattern",x:65,y:50,label:"SPOOFING ML",type:"INTELLIGENCE",risk:"0.89",evidence:"Repeated sequence across sessions"},{id:"trader",x:88,y:22,label:"TRADER T-91",type:"ENTITY",risk:"LINKED",evidence:"Desk + account + supervisor"},{id:"case",x:105,y:60,label:"SUPERVISE",type:"ACTION",risk:"REVIEW",evidence:"Evidence sequence attached"}],edges:[['orders','cancel'],['exec','price'],['cancel','pattern',true],['price','pattern',true],['pattern','trader',true],['pattern','case',true],['trader','case']]},
] as const;

function Graph({story,onSelect,selected}:{story:(typeof stories)[number];onSelect:(id:string)=>void;selected:string}){const node=(id:string)=>story.nodes.find(n=>n.id===id)!;return <svg viewBox="0 0 116 100" className={styles.svg} role="img" aria-label={`${story.label} investigation graph`}><defs><pattern id={`dots-${story.id}`} width="5" height="5" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".25" className={styles.dot}/></pattern><filter id={`glow-${story.id}`}><feGaussianBlur stdDeviation="1.4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect width="116" height="100" fill={`url(#dots-${story.id})`}/>{story.edges.map((e,i)=>{const a=node(e[0]),b=node(e[1]);return <g key={i}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} className={e[2]?styles.hotEdge:styles.edge}/>{e[2]&&<circle r=".9" className={styles.packet}><animateMotion dur={`${1.7+i*.13}s`} repeatCount="indefinite" path={`M${a.x},${a.y} L${b.x},${b.y}`}/></circle>}</g>})}{story.nodes.map((n,i)=><g key={n.id} className={`${styles.node} ${selected===n.id?styles.nodeSelected:""}`} onClick={()=>onSelect(n.id)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")onSelect(n.id)}} aria-label={`${n.label}: ${n.evidence}`}><circle cx={n.x} cy={n.y} r={n.type==="ACTION"||n.type==="CANONICAL"||n.type==="INTELLIGENCE"?5.2:3.6} className={n.type==="ACTION"||n.type==="CANONICAL"||n.type==="INTELLIGENCE"?styles.keyNode:styles.baseNode} style={{animationDelay:`${i*.12}s`}}/><text x={n.x} y={n.y-7} textAnchor="middle">{n.label}</text></g>)}</svg>}

export default function WorkloadGraphs(){const [active,setActive]=useState(0);const [selected,setSelected]=useState(stories[0].nodes[0].id as string);const story=stories[active];const chosen=story.nodes.find(n=>n.id===selected)??story.nodes[0];const change=(i:number)=>{setActive(i);setSelected(stories[i].nodes[0].id)};return <section className={styles.section}><Container size="wide"><Reveal className={styles.head}><MonoLabel tone="accent">FOUR WORKLOADS · FOUR INVESTIGATION GRAPHS</MonoLabel><h2>See how ARGUS finds the risk—not just the alert.</h2><p>Each graph tells a different evidence story. Choose a workload, then select any node to inspect what the intelligence layer knows.</p></Reveal><div className={styles.layout}><div className={styles.tabs} role="tablist" aria-label="ARGUS graph stories">{stories.map((s,i)=>{const Icon=s.icon;return <button type="button" role="tab" aria-selected={i===active} className={i===active?styles.activeTab:""} onClick={()=>change(i)} key={s.id}><Icon/><span>{s.label}</span><small>{i===active?"VIEWING GRAPH":"OPEN GRAPH"}</small></button>})}</div><div className={styles.graphPanel}><div className={styles.graphTop}><span><i/>ARGUS GRAPH · {story.label}</span><b>{story.model}</b></div><Graph story={story} selected={chosen.id} onSelect={setSelected}/><div className={styles.nodeDetail} key={chosen.id}><span>{chosen.type}</span><strong>{chosen.label}</strong><p>{chosen.evidence}</p><b>{chosen.risk}</b></div><div className={styles.verdict}><BrainCircuit/><div><span>INTELLIGENCE OUTCOME</span><strong>{story.verdict}</strong></div><ShieldCheck/></div></div><div className={styles.copy}><span>0{active+1} · {story.label}</span><h3>{story.title}</h3><p>{story.copy}</p><div><Network/><span>Graph evidence</span><BrainCircuit/><span>ML + AI intelligence</span><ShieldCheck/><span>Governed action</span></div></div></div></Container></section>}
